version: '3.8'
services:
  docker-puller:
    image: docker-puller
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./dockerpuller:/usr/src/app/dockerpuller